version: '3.8'

services:
  quote-data-service:
    build:
      context: .
      dockerfile: quote_data_service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

  rate-limiter-service:
    build:
      context: .
      dockerfile: rate_limiter_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge